version: '3.8'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Netmed#1@@
      MYSQL_DATABASE: netmed
      MYSQL_USER: Netmed
      MYSQL_PASSWORD: Netmed#1@@
    ports:
      - "3306:3306"
    network_mode: "host"

  login-interativo:
    build: .
    container_name: login-netmed-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    stdin_open: true # STDIN aberto
    tty: true # aloca terminal tty

